README.md, meson.build
This fills in the Development section of the main README with the Gitflow details from the rt-5gms-application-server project, improves the source downloading section and bumps the version number to 1.0.0 in preparation for release.
=> Prepare for release.

README.md, src/5gmsaf/context.c, src/5gmsaf/context.h, src/5gmsaf/event.c, src/5gmsaf/event.h, src/5gmsaf/init.c, src/5gmsaf/msaf-sm.c, src/5gmsaf/msaf.yaml, src/5gmsaf/sbi-path.c, src/5gmsaf/sbi-path.h
This adds the client side M3 API to the application function.
This allows the 5GMS Application Function to directly configure the 5GMS Application Server.
Therefore, after this change the 5GMS Application Server will no longer be configured separately using the same `ContentHostingConfiguration` JSON file as the Application Function, it will receive the configuration that has been applied to the Application Function via the M3 interface. This requires that the 5GMS Application Server implements the M3 API server (see PR 5G-MAG/rt-5gms-application-server#50).
=> Feature: 5GMS Application Function M3 API

src/5gmsaf/media-player-entry.c, src/5gmsaf/msaf-sm.c, src/5gmsaf/provisioning-session.c, src/5gmsaf/service-access-information.c
Closes #28 
Also adds a little extra logging around ContentHostingConfiguration reading.
=> Fix: Use domainNameAlias for the authority in the mediaPlayerEntry when available and improve error logging by the 5GMS AF

src/5gmsaf/context.c, src/5gmsaf/context.h, src/5gmsaf/meson.build, src/5gmsaf/msaf-sm.c, subprojects/patch_open5gs.sh
This backports, to the v1.0.x branch, the use of domainNameAlias in the Service Access Information and improves the error logging around loading the ContentHostingConfiguration and serving the ServiceAccessInformation.
Fixes #28.
=> Backport Fix to v1.0.x: Use domainNameAlias for the authority in the mediaPlayerEntry when available and improve error logging by the 5GMS AF

src/5gmsaf/application-server-context.c, src/5gmsaf/context.c, src/5gmsaf/msaf-sm.c, src/5gmsaf/provisioning-session.c, src/5gmsaf/utilities.c
This PR applies some changes to improve logging around the reading and parsing of the ContentHostingConfiguration and Certificates JSON files as referred to from the `msaf.yaml` file.
Implements #29 for the development branch.
Improves logging around:
- missing configuration file settings for `msaf/certificates` and `msaf/contentHostingConfiguration`.
- Problems opening the configured files.
- Problems parsing the configured files.
- Problems allocating memory for the parsed data structures.
- Problems validating the consistency of the configuration.
=> Enhancement: improved logging around content hosting configuration and certificates configuration files

meson.build
This prepares for a release of v1.0.1 which includes:
- Improved error logging
- Fix for the domain name used in the M5 ServiceAccessInformation response so that it uses the `domainNameAlias` provided in the ContentHostingConfiguration rather than the canonical hostname of the 5GMS Application Server.
- Build time fixes for sandboxing issues
- Use public URL for rt-common-shared submodule
- Minor documentation fixes.
=> Bump version for v1.0.1 release.

README.md, meson.build
The introduction of the M3 interface marks a significant change in the operation of the 5GMS Application Function, so bumping the version to v1.1.0 for the next release.
I'll tag a release candidate for this when the changes from 5G-MAG/rt-5gms-application-server#55 have been merged.
=> Prepare release candidate for v1.1.0

README.md, src/5gmsaf/meson.build, src/5gmsaf/msaf.yaml
This request includes updates for the documentation to reflect the use of 5GMS v17.3.0 specifications and some details about requiring the 5GMS Application Server to be running.
This will also deploy the default `msaf.yaml` file when the install step of the build is done. This follows the Open5GS method of deploying these configuration files. This means that the configuration file will only be deployed, on install, if you are not deploying to a packager (i.e. `DESTDIR` environment variable is not set) and the configuration file does not already exist in the deployment location (this is to prevent customised configuration files being overwritten on subsequent deployments).
=> Documentation and deployment updates for v1.1.0 release candidate

examples/ContentHostingConfiguration_Big-Buck-Bunny_pull-ingest_domain-name_http.json, examples/ContentHostingConfiguration_Big-Buck-Bunny_pull-ingest_domain-name_http_and_https.json, examples/README.md, examples/Test_http_canonical-msaf.yaml, examples/Test_http_domain_alias-msaf.yaml, examples/Test_https_canonical-msaf.yaml, examples/Test_https_domain_alias-msaf.yaml, src/5gmsaf/application-server-context.c
This PR adds some more example files and improves the logging of M3 requests.
There are new ContentHostingConfiguration JSON files which include a `domainNameAlias` of `media.example.com` for testing those parts of the Application Function which should prefer to use `domainNameAlias` over `canonicalDomainName` (or vice-versa).
There are some testing `msaf.yaml` Application Function YAML configuration files which turn on debug output and reference different ContentHostingConfiguration JSON files. This will make documenting test procedures easier and is a start on automating CI testing.
The examples folder README has also been updated to reflect these changes.
=> Improve examples and logging

README.md, src/5gmsaf/context.c, src/5gmsaf/provisioning-session.c, src/5gmsaf/utilities.c, src/5gmsaf/utilities.h
This PR fixes the issue of relative filenames in the `msaf.yaml` configuration file not being relative to the configuration file itself.
This also introduces a note about the requirement for an Internet connection during build and diagnosing failures to fetch the API or openapi-generator JAR file during building. This supersedes PR #43.
I think this deals with the last issues found by myself while documenting the tests, and by @stepski011 and others while testing.
=> Fix for lack of relative filenames in msaf.yaml and documentation improvements for release candidate

meson.build, src/5gmsaf/meson.build
The recent 3GPP changes to introduce the v17.4.0 API changes to the 5G_APIs repository are breaking the v1.2.0 release of the 5GMS Application Function.
This is a quick fix that forces the version of the 5G_APIs back to the TS 26.512 v17.3.0 release API files by selecting the `TSG98-Rel17` release tag for the 5G_APIs instead of the 'REL-17' branch.
=> Fix: TS 26.512 v17.4.0 APIs rollback for v1.2.x branch

src/5gmsaf/msaf-m5-sm.c, tools/python3/lib/rt_m1_client/session.py, tools/python3/lib/rt_m1_client/types.py
This is a fix for a memory leak when the M5 interface reports that the provisioning session id cannot be found. The error text was being leaked every time this error was generated.
Also fixes a bug introduced in the M5 interface where the wrong HTTP status code was being returned with a service-access-information request response.
This PR also includes some fixes for the `m1-session` tool for matching provisioning sessions by the ingest URL and one entry point relative path, and improvements to the display of ContentHostingConfiguration information.
=> Bug Fixes: Memory leak in AF and fix for m1-session del-stream matching

meson_options.txt, src/5gmsaf/.gitignore, src/5gmsaf/application-server-context.c, src/5gmsaf/application-server-context.h, src/5gmsaf/certmgr.c, src/5gmsaf/certmgr.h, src/5gmsaf/context.c, src/5gmsaf/context.h, src/5gmsaf/generator-5gmsaf, src/5gmsaf/init.c, src/5gmsaf/meson.build, src/5gmsaf/msaf-fsm.c, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/msaf-m5-sm.c, src/5gmsaf/msaf-mgmt-sm.c, src/5gmsaf/msaf-sm.c, src/5gmsaf/msaf.yaml.in, src/5gmsaf/provisioning-session.c, src/5gmsaf/sbi-path.c, src/5gmsaf/server.c, subprojects/patch_open5gs.sh, tools/bash/certmgr, tools/python3/lib/rt_m1_client/certificates/acme_cert_signer.py, tools/python3/lib/rt_m1_client/certificates/base.py, tools/python3/lib/rt_m1_client/certificates/local_ca_cert_signer.py, tools/python3/lib/rt_m1_client/client.py, tools/python3/lib/rt_m1_client/session.py, tools/python3/m1_client_cli.py, tools/python3/m1_session_cli.py, tools/python3/m1_sync_config.py
This PR pulls in some uplifts for:
- TS 26.512 V17.4.0
- Updates `Server` response header to match the change in specification.
- TS 26.512 V17.6.0
- Uses TSG100-Rel17 release of the APIs for the 5GMS AF.
- Adds handling of multiple domain names during CSR creation.
- Open5GS (Release 16 => Release 17 uplift)
It also includes a modification to the 5GMS Application Function build system to automatically determine which OpenAPI model source codes have been generated, and include them in the compile, rather than the files having to be explicitly named in the build file.
Note also that a new configuration file variable, `msaf.m3Host`, has been added so that the 5GMS AF can use an internal network to talk to the 5GMS AS via M3 rather than having to share the canonical hostname (which is used …
=> Uplift to TS 26.512 V17.6.0 and Release 17 version of Open5GS

src/5gmsaf/application-server-context.c, src/5gmsaf/application-server-context.h, src/5gmsaf/certmgr.c, src/5gmsaf/consumption-report-configuration.c, src/5gmsaf/consumption-report-configuration.h, src/5gmsaf/context.c, src/5gmsaf/generator-5gmsaf, src/5gmsaf/init.c, src/5gmsaf/meson.build, src/5gmsaf/msaf-fsm.h, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/msaf-m5-sm.c, src/5gmsaf/msaf.yaml.in, src/5gmsaf/provisioning-session.c, src/5gmsaf/provisioning-session.h, src/5gmsaf/response-cache-control.c, src/5gmsaf/response-cache-control.h, src/5gmsaf/server.c, src/5gmsaf/server.h, src/5gmsaf/service-access-information.c, src/5gmsaf/utilities.c, tools/python3/lib/rt_m1_client/client.py, tools/python3/lib/rt_m1_client/session.py, tools/python3/lib/rt_m1_client/types.py, tools/python3/m1_client_cli.py, tools/python3/m1_session_cli.py, tools/python3/m1_sync_config.py
This change adds the Consumption Reporting Provisioning API to the interface at M1 and updates the M1 command line tools with the new operations.
This change also includes a few bug fixes, code improvements and the missing OPTIONS for the content protocols discovery API on M1.
The consumption reporting configuration is implemented as a single optional instance held in the provisioning session.
The GET, PUT, POST, DELETE and OPTIONS operations have been implemented. The PATCH operation has not been implemented.
The python tools now accept new commands or configuration in order to configure a consumption reporting configuration.
- `m1-client`
- `m1-client consumption create <address:port> <provisioning-session-id> [-i SECONDS] [-p PERCENT] [-l] [-a]` - Add a new consumption reporting …
=> Feature: M1 - Consumption Reporting Provisioning

meson.build, src/5gmsaf/consumption-report-configuration.c, src/5gmsaf/context.c, src/5gmsaf/meson.build, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/msaf-m5-sm.c, src/5gmsaf/provisioning-session.c, src/5gmsaf/provisioning-session.h, src/5gmsaf/sai-cache.c, src/5gmsaf/sai-cache.h, src/5gmsaf/service-access-information.c, src/5gmsaf/service-access-information.h, tests/meson.build, tests/msaf/abts-main.c, tests/msaf/meson.build, tests/msaf/sai-cache-test.c, tests/msaf/sai-cache-test.h, tests/msaf/tests.c, tests/msaf/tests.h
This adds the `clientConsumptionReportingConfiguration` field to the Service Access Information (SAI) response at interface reference point M5 if a *ConsumptionReportingConfiguration* is set on the Provisioning Session.
The `ServiceAccessInformation.clientConsumptionReportingConfiguration.serverAddresses` contains a list of M5 API access URLs. To guarantee that the UE that has requested the SAI can also access the Consumption Reporting interface (on the same interface at reference point M5), this list is set to contain server addresses based on the `Host` and access protocols used to request the Service Access Information. This means that responses for requests using different URL protocols and authorities will be given responses with different server addresses. To make this efficient and …
=> Feature: SAI - Consumption Reporting

src/5gmsaf/context.c, src/5gmsaf/context.h, src/5gmsaf/data-collection.c, src/5gmsaf/data-collection.h, src/5gmsaf/generator-5gmsaf, src/5gmsaf/meson.build, src/5gmsaf/msaf-m5-sm.c, src/5gmsaf/msaf.yaml.in
This adds the ConsumptionReporting API to the interface at reference point M5.
This is a simple API with only one `POST` operation to allow a 5GMS Aware App to submit a consumption report. The App's consumption reporting is controlled using the `clientConsumptionReportingConfiguration` returned in the `ServiceAccessInformation` (see #93).
This PR adds that `POST` operation along with `OPTIONS` operations for both the service access information and consumption reporting APIs on the interface at reference point M5.
This also introduces a Data Collection function to store the data into a data collection reports directory. The directory is controlled by the `msaf.dataCollectionDir` configuration parameter in the YAML configuration file. If not present in the configuration then no reports will …
=> Feature: Add M5 ConsumptionReporting API

src/5gmsaf/consumption-report-configuration.c, src/5gmsaf/consumption-report-configuration.h, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/service-access-information.c
Adds some field validation to the AF to stop the python tool rejecting things that the AF has accepted.
Forces the output of the `accessReporting` field in M5 Service Access Information.
Closes #98, closes #99
=> Fix: ConsumptionReportConfiguration validation and accessReporting field

tools/python3/m1_sync_config.py
Adds the *canonicalDomainName* field values, from ContentHostingConfigurations, to the list of domains to publish the `m8.json` file to.
This is a fix for an issue noticed on the Linode VM.
Closes #101
=> Bug-fix: Use canonical domain in publication dirs

tools/bash/le-certmgr, tools/meson.build
Adds a Let's Encrypt certificate Manager script (based on the self-signed Certificate Manager) which will use the `certbot` command to generate or revoke let's encrypt signed certificates.
Change the `msaf.certificateManager` property in the `msaf.yaml` to `$prefix/libexec/rt-5gms/lets-encrypt-certmgr` (where `$prefix` is your installation prefix) to use this certificate manager instead of the default self-signed certificate manager.
Closes #71
=> Enhancement: Add Let's Encrypt Certificate Manager for the AF to use.

README.md, src/5gmsaf/provisioning-session.c, tools/python3/lib/rt_m1_client/session.py, tools/python3/m1_session_cli.py, tools/python3/m1_sync_config.py
This PR adds the ability for the `msaf-configuration` tool to pick up a `streams.policies` section of the _streams.json_ file.
The data in this section is used to synchronise PolicyTemplates for the provisioning session by utilising the M1 reference point of the 5GMS AF.
This also adds the output of policy template ids for the provisioning session in the ProvisioningSession object and fixes some caching issues for Policy Templates in the M1Session python class.
The final part is documentation to note that the REASON project funded some of the development of the Network Assistance and Dynamic Policies features.
=> Add PolicyTemplates to the msaf-configuration tool

README.md
When doing a clean installation on an Ubuntu22 machine I ran into two minor issues with cmake and OpenSSL not being found. Adding them to the list of dependencies in the Readme.
=> Add cmake and pyOpenSSL as dependencies in README.md

examples/ConsumptionReportingConfiguration.json, meson_options.txt, src/5gmsaf/consumption-report-configuration.c, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/msaf-m5-sm.c, src/5gmsaf/policy-template.c, src/5gmsaf/policy-template.h, src/5gmsaf/provisioning-session.c, src/5gmsaf/provisioning-session.h, src/5gmsaf/service-access-information.c, tools/python3/lib/rt_m1_client/client.py, tools/python3/lib/rt_m1_client/types.py
This updates the code in line with changes agreed for 3GPP TS 26.512 v17.7.0.
Closes #112 
Closes #113
Closes #115 
Please see #112 and #113 for full details of the v17.7.0 changes, and #115 for the changes needed to accommodate the clarification of consumption reporting in v17.7.0.
=> Enhancement: Uplift to TS26.512 v17.7.0

examples/PolicyTemplate-1.json, examples/PolicyTemplate-1b.json, examples/PolicyTemplate-2.json, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/openapi-templates/model-body.mustache, src/5gmsaf/utilities.c, src/5gmsaf/utilities.h, tests/msaf/meson.build, tests/msaf/tests.c, tests/msaf/utilities-test.c, tests/msaf/utilities-test.h, tools/python3/lib/rt_m1_client/types.py
These fix issues with the validation of fields in the Policy Templates where the field type is a string restricted by a regex in the OpenAPI and fixes a bug in number range validation for integer types.
This addresses #120, #121, #122  and #124.
=> Bug fix: Policy templates field validation

.gitmodules, meson.build, src/5gmsaf/generator-5gmsaf, src/5gmsaf/local.c, src/5gmsaf/policy-template.c, src/5gmsaf/provisioning-session.c, src/5gmsaf/service-access-information.c, subprojects/.gitignore, subprojects/open5gs.wrap, subprojects/packagefiles/open5gs.patch, tests/msaf/sai-cache-test.c
The rt-5gc-data-collection-application-function and rt-5gms-application-function need to use the same openapi-generator templates and patches to open5gs. Therefore the OpenAPI C code templates have been moved from the 5GMS AF to rt-common-shared (PR 5G-MAG/rt-common-shared#31) and the common open5gs patches have been placed on a "bbc-patches" branch on the 5G-MAG/open5gs fork.
This PR makes the changes to the 5GMS AF source to use these 2 common places for the templates and open5gs patches instead of doing both inside the rt-5gms-application-function repository.
Note: PR 5G-MAG/rt-common-shared#31 introduces a change to how OpenAPI enumerated types are represented in the code to disambiguate internal values (*NULL*) from enumerated values by prefixing the enumerated values with "VAL_". …
=> Enhancement: Use new branches and common areas in 5G-MAG/open5gs and 5G-MAG/rt-common-shared

src/5gmsaf/5G_APIs-overrides/TS26512_M1_MetricsReportingProvisioning.yaml, src/5gmsaf/5G_APIs-overrides/TS26512_M5_DynamicPolicies.yaml, src/5gmsaf/generator-5gmsaf, src/5gmsaf/openapi-extra-yaml/Maf_Management.yaml
This is the rt-5gms-application-function counter-part PR to 5G-MAG/rt-common-shared#34.
This updates the 5GMS Application Function to use the new locations for the OpenAPI generator script and templates directories.
=> Use new paths for Open5GS OpenAPI generator script and templates

src/5gmsaf/msaf-m1-sm.c
This change is adressing the error of absent `Location` header from the response upon successful creation of Metrics Configuration at M1 interface.
Related issue: https://github.com/5G-MAG/rt-5gms-application-function/issues/140
=> Location header included for creation of Metrics Configuration

src/5gmsaf/service-access-information.c
This PR adds value checking for provisioned metrics configuration's `scheme`. If the value is missing from M1 *Create* operation, it will be assigned with `urn:‌3GPP:‌ns:‌PSS:‌DASH:‌QM10` scheme.
Note that according to TS26.512 (v17.7) `scheme` is not mandatory field for M1 Metrics  *Create* operation (Table 7.8.3-1). However it's required for the `clientMetricsReportingConfigurations` as part of Service Access Information (Table 11.2.3.1-1).
#151
=> QoE Metrics Reporting | Handling of missing scheme value

src/5gmsaf/msaf-m5-sm.c
Fixes parsing of `clientID` field of incoming metrics data.
Related issue: https://github.com/5G-MAG/rt-5gms-application-function/issues/154
=> Fixed parsing client id value from QoE metrics

src/5gmsaf/msaf-m1-sm.c
This fixes the HTTP response message to the _activateConsumptionReporting_ operation at reference point M1 in line with the YAML API specification in TS 26.512 V17.7.0:
- Add missing `Location` header.
- Change the status code from *204 No Content* to *201 Created*.
Fixes #156 and #157
=> Bug-fix: Response message for activateConsumptionReporting operation at M1

meson.build, src/5gmsaf/msaf-m1-sm.c
Fixes 5G-MAG/rt-5gms-application-provider#45
If the `open5gsIntegration` YAML configuration file variable is not true then this removes the `Allow: POST` response header from the headers returned for the `OPTIONS` method on the `.../provisioning-sessions/{provisioningSessionId}/policy-templates` M1 API path. This allows the UI to detect if provisioning of PolicyTemplates will be allowed or not.
=> Reflect the enabled state of PolicyTemplate provisioning in the OPTIONS method

meson_options.txt, src/5gmsaf/consumption-report-configuration.c, src/5gmsaf/consumption-report-configuration.h, src/5gmsaf/dynamic-policy.c, src/5gmsaf/generator-5gmsaf, src/5gmsaf/meson.build, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/msaf-m5-sm.c, src/5gmsaf/msaf-mgmt-sm.c, src/5gmsaf/msaf-sm.c, src/5gmsaf/network-assistance-session.c, src/5gmsaf/policy-template.c, src/5gmsaf/policy-template.h, src/5gmsaf/provisioning-session.c, src/5gmsaf/provisioning-session.h, src/5gmsaf/server.c, src/5gmsaf/server.h, src/5gmsaf/service-access-information.c
Fixes #163 
These changes, combined with 5G-MAG/rt-common-shared#39, implement the uplift to TS 26.512 and include some bug fixes for issues found during testing.
The major changes are:
1. Compliance with the TS 26.512 V17.9.1 specification.
- No new API interfaces have been added only the existing ones have been brought inline with V17.9.1.
2. Error responses now include `invalidParameters`, where appropriate, in the ProblemReport JSON to indicate the field that caused the error.
3. Changes in the templates, implemented by PR 5G-MAG/rt-common-shared#39, have added Date-Time, Date, URL, UUID and custom *pattern* string validation to the OpenAPI generated parsers.
- This means the AF will now be a bit stricter about the format of certain string fields passed in on the M1 and M5 API …
=> Uplift to 3GPP TS 26.512 V17.9.1

README.md, src/5gmsaf/metrics-reporting-configuration.c, src/5gmsaf/msaf-m1-sm.c, src/5gmsaf/provisioning-session.c
This PR make a few minor updates:
1. The README is updated to reflect the need for the PCRE v2 library (development package) when building. This is needed after the introduction of regex pattern validation where indicated for string fields in code generated from OpenAPI models.
2. The README is updated to bring the system meson build up to date for package installation (`sudo meson ...` is used for installation to system paths).
3. Some minor memory leak bugs were found when testing for 5G-MAG/rt-5gms-application-provider#48 and have been fixed here.
=> Bug-fix: Update README for new dependencies and meson version consistency

README.md
* Adds a link to the Docker Compose setup located in rt-5gms-examples: https://github.com/5G-MAG/rt-5gms-examples/pull/13
* Reformats a few lines
=> Add one small section about the Docker setup to the documentation.
